// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docsSidebar: [
    {
      type: 'category',
      label: 'Docs',
      items: ['helpful-docs/npm'],
    },
  ],
  projectsSidebar: [
    {
      type: 'category',
      label: 'Projects',
      items: ['projects/Collaboration', 'projects/Documentation', 'projects/Projects'],
    },
  ],
  learningSidebar: [
    {
      type: 'category',
      label: 'Learning',
      items: ['learning/Learnings'],
    },
  ],
  meSidebar: [
    {
      type: 'category',
      label: 'Me',
      items: [
        'me/Goals/Company',
        'me/Goals/Goals',
        'me/Goals/Recognition',
      ],
    },
    {
      type: 'category',
      label: 'Weekly',
      items: [
        'me/weekly/To-Do',
        'me/weekly/1.6.25',
        'me/weekly/1.13.25',
      ],
    },
    {
      type: 'category',
      label: '1:1',
      items: ['me/1:1/wc'],
    },
  ]
};

export default sidebars;
